Improve pre-commit hooks with better go and python linting (#6)

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -9,31 +9,46 @@ for FILE in $JAVASCRIPT_FILES
 do
     eslint "$ROOT/$FILE"
     if [[ "$?" == 0 ]]; then
-        echo "ESLint passed: $FILE"
+        echo "esLint passed: $FILE"
     else
-        echo "ESLint failed: $FILE"
+        echo "esLint failed: $FILE"
         PASS=false
     fi
 done
 
 cd $ROOT/fwends-backend
 GO_FILES=$(git diff --cached --name-only --diff-filter=ACM . | grep ".go$")
-if [ -n "${GO_FILES}" ]; then
-    go vet ./...
+for FILE in $GO_FILES
+do
+    go vet "$ROOT/$FILE"
     if [[ "$?" == 0 ]]; then
-        echo "Go vet passed"
+        echo "go vet passed: $FILE"
     else
-        echo "Go vet failed"
+        echo "go vet failed: $FILE"
         PASS=false
     fi
-    staticcheck ./...
+    staticcheck "$ROOT/$FILE"
     if [[ "$?" == 0 ]]; then
-        echo "Go staticcheck passed"
+        echo "go staticcheck passed: $FILE"
     else
-        echo "Go staticcheck failed"
+        echo "go staticcheck failed: $FILE"
         PASS=false
     fi
-fi
+done
+
+cd $ROOT/fwends-test
+PYTHON_FILES=$(git diff --cached --name-only --diff-filter=ACM . | grep ".py$")
+for FILE in $PYTHON_FILES
+do
+    pylint "$ROOT/$FILE"
+    if [[ "$?" == 0 ]]; then
+        echo "pylint passed: $FILE"
+    else
+        echo "pylint failed: $FILE"
+        PASS=false
+    fi
+done
+
 
 if ! $PASS; then
     exit 1
