Add pylint to pre-commit hook

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -9,9 +9,9 @@ for FILE in $JAVASCRIPT_FILES
 do
     eslint "$ROOT/$FILE"
     if [[ "$?" == 0 ]]; then
-        echo "ESLint passed: $FILE"
+        echo "esLint passed: $FILE"
     else
-        echo "ESLint failed: $FILE"
+        echo "esLint failed: $FILE"
         PASS=false
     fi
 done
@@ -22,19 +22,33 @@ for FILE in $GO_FILES
 do
     go vet "$ROOT/$FILE"
     if [[ "$?" == 0 ]]; then
-        echo "Go vet passed: $FILE"
+        echo "go vet passed: $FILE"
     else
-        echo "Go vet failed: $FILE"
+        echo "go vet failed: $FILE"
         PASS=false
     fi
     staticcheck "$ROOT/$FILE"
     if [[ "$?" == 0 ]]; then
-        echo "Go staticcheck passed: $FILE"
+        echo "go staticcheck passed: $FILE"
     else
-        echo "Go staticcheck failed: $FILE"
+        echo "go staticcheck failed: $FILE"
         PASS=false
     fi
 done
+
+cd $ROOT/fwends-test
+PYTHON_FILES=$(git diff --cached --name-only --diff-filter=ACM . | grep ".py$")
+for FILE in $PYTHON_FILES
+do
+    pylint "$ROOT/$FILE"
+    if [[ "$?" == 0 ]]; then
+        echo "pylint passed: $FILE"
+    else
+        echo "pylint failed: $FILE"
+        PASS=false
+    fi
+done
+
 
 if ! $PASS; then
     exit 1
